"""empty message

Revision ID: 2a3c2debe6f2
Revises: ca7f84917681
Create Date: 2023-08-16 20:51:58.914827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3c2debe6f2'
down_revision = 'ca7f84917681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=500), nullable=False))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
